- name: Copy Docker Compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/docker-compose.yml
  become: true

- name: Copy Nginx Configuration template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /home/ubuntu/nginx.conf
  become: true

- name: Pull and restart Docker Compose services
  ansible.builtin.shell:
    cmd: cd /home/ubuntu && export TAG_API={{ tag_api }} && export TAG_WEB={{ tag_web }} && docker compose up -d
  become: true
