on:
  push:
    branches:
      - feature/nginx-template # Workflow trigger on pushes to this branch

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:

    #Checkout the code from repository
    - name: Checkout the code
      uses: actions/checkout@v4

    #Login to Docker hub 
    #using docker/login-action
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    #Build and push the docker image to the docker hub 
    #using docker/build-push-action
    - name: Build and push to Docker hub
      uses: docker/build-push-action@v6
      with: 
        context: ./api
        push: true
        #tagging the built image
        tags: ${{ vars.DOCKERHUB_USERNAME }}/github-actions-api:${{ vars.API_TAG }}, ${{ vars.DOCKERHUB_USERNAME }}/github-actions-api:v${{ github.run_number }}.${{ github.run_attempt }}

  build-web:
    runs-on: ubuntu-latest

    steps:

    #Checkout the code from repository
    - name: Checkout the code
      uses: actions/checkout@v4

    #Login to Docker hub 
    #using docker/login-action
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    #Build and push the docker image to the docker hub 
    #using docker/build-push-action
    - name: Build and push to Docker hub
      uses: docker/build-push-action@v6
      with: 
        context: ./web
        push: true
        #tagging the built image
        tags: ${{ vars.DOCKERHUB_USERNAME }}/github-actions-web:${{ vars.WEB_TAG }}, ${{ vars.DOCKERHUB_USERNAME }}/github-actions-web:v${{ github.run_number }}.${{ github.run_attempt }}
  
  deployAnsible:
    runs-on: ubuntu-latest
    needs: [build-web, build-api]

    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible      
      
      - name: run ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook-install-docker.yml
          key: ${{ secrets.UBUNTU_SSH_KEY }}
          options: 
            -i inventory
 
  
  
